"""同步表注册：元数据（中文名/分组/日期列/回填命令）集中在此。

api.routers.sync 与 fetcher.sync_status 共用，避免两处漂移。
"""

# key / 中文名 / 分组 / 日期列(None=无) / 回填模块 / --only 参数
# module: fundamentals | extra | full | None
TABLES = [
    {"key": "daily_bars", "name": "行情日线", "group": "行情",
     "date_col": "trade_date", "module": None, "only": None},
    # 基本面
    {"key": "company_info", "name": "公司基本信息", "group": "基本面",
     "date_col": None, "module": "fundamentals", "only": None},
    {"key": "fin_income", "name": "利润表", "group": "基本面",
     "date_col": "report_date", "module": "fundamentals", "only": None},
    {"key": "fin_balance", "name": "资产负债表", "group": "基本面",
     "date_col": "report_date", "module": "fundamentals", "only": None},
    {"key": "fin_cashflow", "name": "现金流量表", "group": "基本面",
     "date_col": "report_date", "module": "fundamentals", "only": None},
    {"key": "fin_indicator", "name": "财务指标", "group": "基本面",
     "date_col": "report_date", "module": "fundamentals", "only": None},
    {"key": "main_business", "name": "主营业务(EM)", "group": "基本面",
     "date_col": "report_date", "module": "fundamentals", "only": None},
    {"key": "top_holders", "name": "十大股东", "group": "基本面",
     "date_col": "report_date", "module": "fundamentals", "only": None},
    {"key": "holder_number", "name": "股东人数", "group": "基本面",
     "date_col": "report_date", "module": "fundamentals", "only": None},
    {"key": "pledge_info", "name": "股权质押", "group": "基本面",
     "date_col": "stat_date", "module": "fundamentals", "only": None},
    # 增量
    {"key": "daily_basic", "name": "每日指标", "group": "增量",
     "date_col": "trade_date", "module": "extra", "only": "daily_basic"},
    {"key": "moneyflow", "name": "资金流向", "group": "增量",
     "date_col": "trade_date", "module": "extra", "only": "moneyflow"},
    {"key": "suspend", "name": "停复牌", "group": "增量",
     "date_col": "suspend_date", "module": "extra", "only": "moneyflow"},
    {"key": "dividend", "name": "分红送股", "group": "增量",
     "date_col": "ann_date", "module": "extra", "only": "dividend"},
    {"key": "forecast", "name": "业绩预告", "group": "增量",
     "date_col": "ann_date", "module": "extra", "only": "forecast"},
    {"key": "express", "name": "业绩快报", "group": "增量",
     "date_col": "ann_date", "module": "extra", "only": "forecast"},
    # 全量接口
    {"key": "fina_mainbz", "name": "主营构成", "group": "全量接口",
     "date_col": "end_date", "module": "full", "only": "mainbz"},
    {"key": "company_detail", "name": "公司详情", "group": "全量接口",
     "date_col": None, "module": "full", "only": "company_detail"},
    {"key": "namechange", "name": "曾用名", "group": "全量接口",
     "date_col": "start_date", "module": "full", "only": "namechange"},
    {"key": "top_list", "name": "龙虎榜", "group": "全量接口",
     "date_col": "trade_date", "module": "full", "only": "top_list"},
    {"key": "top_inst", "name": "机构明细", "group": "全量接口",
     "date_col": "trade_date", "module": "full", "only": "top_list"},
    {"key": "index_daily", "name": "指数日线", "group": "全量接口",
     "date_col": "trade_date", "module": "full", "only": "index"},
    {"key": "moneyflow_hsgt", "name": "北向资金", "group": "全量接口",
     "date_col": "trade_date", "module": "full", "only": "hsgt_flow"},
    {"key": "hsgt_top10", "name": "陆股通十大", "group": "全量接口",
     "date_col": "trade_date", "module": "full", "only": "hsgt_top10"},
    {"key": "disclosure_date", "name": "披露计划", "group": "全量接口",
     "date_col": "end_date", "module": "full", "only": "disclosure"},
    {"key": "margin", "name": "两融汇总", "group": "全量接口",
     "date_col": "trade_date", "module": "full", "only": "margin"},
    {"key": "margin_detail", "name": "两融明细", "group": "全量接口",
     "date_col": "trade_date", "module": "full", "only": "margin"},
    {"key": "stk_limit", "name": "涨跌停", "group": "全量接口",
     "date_col": "trade_date", "module": "full", "only": "stk_limit"},
    {"key": "fina_audit", "name": "审计意见", "group": "全量接口",
     "date_col": "end_date", "module": "full", "only": "fina_audit"},
    {"key": "new_share", "name": "IPO新股", "group": "全量接口",
     "date_col": "list_date", "module": "full", "only": "new_share"},
    {"key": "managers", "name": "管理层", "group": "全量接口",
     "date_col": None, "module": "full", "only": "managers"},
    {"key": "share_float", "name": "限售解禁", "group": "全量接口",
     "date_col": "float_date", "module": "full", "only": "share_float"},
    {"key": "block_trade", "name": "大宗交易", "group": "全量接口",
     "date_col": "trade_date", "module": "full", "only": "block_trade"},
    {"key": "adj_factor", "name": "复权因子", "group": "全量接口",
     "date_col": "trade_date", "module": "full", "only": "adj_factor"},
    {"key": "holder_trade", "name": "股东增减持", "group": "全量接口",
     "date_col": "ann_date", "module": "full", "only": "holdertrade"},
    {"key": "daily_ts", "name": "A股日线(Tushare)", "group": "全量接口",
     "date_col": "trade_date", "module": "full", "only": "daily_ts"},
    {"key": "repurchase", "name": "股票回购", "group": "全量接口",
     "date_col": "ann_date", "module": "full", "only": "repurchase"},
    {"key": "pledge_detail", "name": "质押明细", "group": "全量接口",
     "date_col": "ann_date", "module": "full", "only": "pledge_detail"},
    {"key": "index_basic", "name": "指数基本信息", "group": "全量接口",
     "date_col": None, "module": "full", "only": "index_info"},
    {"key": "index_weight", "name": "指数权重", "group": "全量接口",
     "date_col": "trade_date", "module": "full", "only": "index_info"},
    {"key": "index_member", "name": "指数成分", "group": "全量接口",
     "date_col": None, "module": "full", "only": "index_info"},
    {"key": "cyq_perf", "name": "每日筹码分布", "group": "全量接口",
     "date_col": "trade_date", "module": "full", "only": "cyq_perf"},
    {"key": "hk_hold", "name": "沪深港股通持股", "group": "全量接口",
     "date_col": "trade_date", "module": "full", "only": "hk_hold"},
]

# 回填任务 --only → 受影响的业务表（任务结束后刷新这些表的 sync_status）
JOB_TABLES = {
    # extra
    "daily_basic": ["daily_basic"],
    "moneyflow": ["moneyflow", "suspend"],
    "dividend": ["dividend"],
    "forecast": ["forecast", "express"],
    # full
    "company_detail": ["company_detail"],
    "namechange": ["namechange"],
    "new_share": ["new_share"],
    "disclosure": ["disclosure_date"],
    "index": ["index_daily"],
    "hsgt_flow": ["moneyflow_hsgt"],
    "hsgt_top10": ["hsgt_top10"],
    "margin": ["margin", "margin_detail"],
    "top_list": ["top_list", "top_inst"],
    "stk_limit": ["stk_limit"],
    "mainbz": ["fina_mainbz"],
    "fina_audit": ["fina_audit"],
    "managers": ["managers"],
    "share_float": ["share_float"],
    "block_trade": ["block_trade"],
    "adj_factor": ["adj_factor"],
    "holdertrade": ["holder_trade"],
    "daily_ts": ["daily_ts"],
    "repurchase": ["repurchase"],
    "pledge_detail": ["pledge_detail"],
    "index_info": ["index_basic", "index_weight", "index_member"],
    "cyq_perf": ["cyq_perf"],
    "hk_hold": ["hk_hold"],
    # fundamentals（整包）
    "fundamentals": [
        "company_info", "fin_income", "fin_balance", "fin_cashflow",
        "fin_indicator", "main_business", "top_holders", "holder_number",
        "pledge_info", "holder_trade",
    ],
}

# 按日更新的日期列（最新 < 今天即需更新）；其余日期列按季度判定
DAILY_COLS = {"trade_date", "suspend_date", "ann_date", "float_date"}

TABLE_BY_KEY = {t["key"]: t for t in TABLES}
